name: Go release

on:
  release:
    types: [published]
    

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: windows/386, windows/amd64
        goarch: ["386", amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Go release
        uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: windows
          goarch: ${{ matrix.goarch }}
          binary_name: "isup"
          asset_name: isup-${{ matrix.goarch }}
          compress_assets: OFF